run brew fix
I would have run the fix command, but my git is acting up or I am doing something wrong. So when I try to push my local changes this happens:

tf@Mac-Pro homebrew-cask % git push Technofrikus vial-branch
To github.com:Technofrikus/homebrew-cask.git
 ! [rejected]              vial-branch -> vial-branch (fetch first)
error: failed to push some refs to 'github.com:Technofrikus/homebrew-cask.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.

I was not able to solve this, so I just added the zap stanza by hand on github directly. Didnt think of copying the complete text from my local file and just pasting it after running brew fix. So that is what I did now. Hope this solves everything.