Fix plugdata.rb case-sensitivity
Changed package name to match the case of that provided by the PlugData releases, since a mismatch was causing installation to fail on macOS case-sensitive file systems:

```
❯ brew install --cask plugdata
==> Downloading https://github.com/timothyschoen/PlugData/releases/download/v0.6.4/PlugData-MacOS-Universal.pkg
Already downloaded: /Users/leigh/Library/Caches/Homebrew/downloads/6eaaea1db48d61658a20a9669306f459060481a45cd6114f67b61e92e492d740--plugdata-macOS-Universal.pkg
==> Installing Cask plugdata
==> Running installer for plugdata; your password may be necessary.
Package installers may write to any location; options such as `--appdir` are ignored.
==> Purging files for version 0.6.4 of Cask plugdata
Error: Could not find PKG source file 'PlugData-MacOS-Universal.pkg', found 'plugdata-macOS-Universal.pkg' instead.
```