Update to correct sha256
Fix the sha256.

08:42 $ brew cask install teamviewer
==> Downloading https://download.teamviewer.com/download/version_12x/TeamViewer.dmg
######################################################################## 100.0%
==> Verifying checksum for Cask teamviewer
==> Note: running "brew update" may fix sha256 checksum errors
Error: sha256 mismatch
Expected: 1dc2dda560dc8a70b6478e7e88b1c64d9b0f6a8db24c8d165c2b2e14e2de55ee
Actual: 5570875f99f2be0fdc167366c11e80056fa9e3d617e9b731e7821a81e2e1df45
File: /Users/jball/Library/Caches/Homebrew/Cask/teamviewer--12.0.72647.dmg
To retry an incomplete download, remove the file above.