fig: Remove broken zap script (#143867)
The script is part of the app but runs after the zap, not before, so it no longer exists:

==> Running uninstall script /Applications/Fig.app/Contents/MacOS/fig-darwin-universal
Error: uninstall script /Applications/Fig.app/Contents/MacOS/fig-darwin-universal does not exist.

Zapping implies uninstalling, which happens first, so the script isn't necessary anyway.