Update powershell@preview.rb
Should this now be deleted given the cask has been removed? The SHA stops installs regardless.

```
Warning: powershell@preview has been deprecated because it does not pass the macOS Gatekeeper check! It will be disabled on 2026-09-01.
✘ Cask powershell@preview (7.6.0-rc.1)                                                     Verifying    72.5MB/ 72.5MB
Error: Cask reports different checksum:     2fa0f6ca832cc58386287495ce4c9e5c5ce7bbaed210b071d1a676e9789ee8cc
       SHA-256 checksum of downloaded file: 6ab6fd945b195ed4a9ae6d2be3fea3172ca158505707561ba74822dd4165f759
```

```
powershell-7.6.0-rc.1-osx-arm64.pkg
6AB6FD945B195ED4A9AE6D2BE3FEA3172CA158505707561BA74822DD4165F759
```

https://github.com/powershell/powershell/releases