Update tether to 1.5.14
1.3.0 is no longer listed on their servers and returns a 404 from `brew
cask install tether`:

```
curl: (22) The requested URL returned error: 404 Not Found
Error: Download failed on Cask 'tether' with message: Download failed:
http://hellotether.com/downloads/Tether_v1.3.0.zip
```