Update pokerstars.rb (#71091)
Fails cask style check for missing forward slash.

== /usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/pokerstars.rb ==
C: 31: 12: 'https://www.pokerstars#{language[0]}' must have a slash after the domain.

1 file inspected, 1 offense detected
Error: Style check failed.