fix install sketchup because of mismatch sha256
Install sketchup fail because of mismatch sha256:
```
$ brew cask install sketchup
==> Downloading https://dl.trimble.com/sketchup/SketchUpMake-en.dmg
######################################################################## 100,0%
==> Verifying checksum for Cask sketchup
==> Note: running "brew update" may fix sha256 checksum errors
Error: sha256 mismatch
Expected: a61e7e55b42e8d2e4735c4e45f0d53435c8dfd4f6aaca7187b4f945a58acc858
Actual: 9a515fac2a3a4c0d32c90c2570e887395ae5c79511310d183624f24a6e436efa
File: /Users/cyril.lakech/Library/Caches/Homebrew/Cask/sketchup--2017.dmg
To retry an incomplete download, remove the file above.

I just updated the sha256...