disable minitest-colorize
solves this error:
```bash
$ bundle exec rake test
...lib/minitest/colorize.rb:88:in `<top (required)>': undefined method `output=' for Minitest::Unit:Class (NoMethodError)
...
```