Update XQuartz 2.8.1 pkg file name
XQuartz won't install on a case sensitive file system, because the file name differs in the actual DMG image: 

```➜  ~ brew install xquartz
==> Downloading https://github.com/XQuartz/XQuartz/releases/download/XQuartz-2.8.1/XQuartz-2.8.1.dmg
Already downloaded: /Users/user/Library/Caches/Homebrew/downloads/d919462a1157a8871a5564342d93589799c4e38d29e86059dd37b1b0b3ac4ee1--XQuartz-2.8.1.dmg
==> Installing Cask xquartz
==> Running installer for xquartz; your password may be necessary.
Package installers may write to any location; options such as `--appdir` are ignored.
==> Purging files for version 2.8.1 of Cask xquartz
Error: Could not find PKG source file 'Xquartz.pkg', found 'XQuartz.pkg' instead.
```

The file name for XQuartz 2.8.0 was actually changed in https://github.com/Homebrew/homebrew-cask/issues/102559, it seems like the developers changed it back to the original filename.