Update SHASUMS for vagrant-vmware-utility
This is required, as users are currently seeing SHASUM mismatches when trying to install vagrant-vmware-utility via the official tap. The apple artifacts were resigned and renotarized, and shasums were updated, as part of hashicorp maintenance this morning (more info in https://status.hashicorp.com/incidents/xbbwr755y78b). After this is merged, users will need to run `brew update` to get the updated SHASUMS: 

```
elle@elle-LD64KN442W Downloads % brew install vagrant-vmware-utility
==> Downloading https://releases.hashicorp.com/vagrant-vmware-utility/1.0.21/vagrant-vmware-utility_1.0.21_x86_64.dmg
######################################################################## 100.0%
Error: SHA256 mismatch
Expected: d05999fd5eecd1e7faf2086846b3ba0e5d5f4c2f20574ec371d74f27f7f99f5e
  Actual: feca4c6ff3d9edd41b97614ace7998ed048e58e30af534aa131a0b241b55df7b
    File: /Users/elle/Library/Caches/Homebrew/downloads/92e4d801c06f814ba12d6023bf87a6f8a16e5205c8d56665769c4ca782d50434--vagrant-vmware-utility_1.0.21_x86_64.dmg
To retry an incomplete download, remove the file above.
```