Update Flux to remove version from URL
The url does not actually have a version. This causes the following failures:
```
> brew cask install flux
==> Downloading https://justgetflux.com/mac/Flux40.1.zip
##O#- #
curl: (60) SSL certificate problem: certificate has expired
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
Error: Download failed on Cask 'flux' with message: Download failed: https://justgetflux.com/mac/Flux40.1.zip
```